### ISSUE TITLE
App won't start from GNOME Shell, but will start from GNOME Software or Terminal

### ISSUE THREAD

**Issue by Tuba2** [ItsJamie9494/window-painter#4]
## Affected version

 1.1.0
Flatpak (Flathub)

## System

Fedora Linux 37 (Workstation Edition) x86_64
GNOME 43.3
Wayland
Intel i7-3520M

## Bug summary
Whenever I try to launch Window Painter from the app grid or search in GNOME Shell, the app just doesn't show up.
There is a brief spinning animation on the cursor and on the GNOME top panel, as if the application was still loading, but it ceases quickly.

However, if I start the app from GNOME Software or Terminal, it shows up just fine.
Terminal reports an error, though, and I suspect this is the culprit:

```** (process:16060): WARNING **: 01:11:17.957: Error writing credentials to socket: Erro ao enviar mensagem: Pipe quebrado```

It's partially in Portuguese, but it translates to:

```** (process:16060): WARNING **: 01:11:17.957: Error writing credentials to socket: Error while sending message: Broken pipe```

After that I decided to check if it was starting but quickly being shut down, and found out it would briefly appear listed in the System Monitor when launched from GNOME Shell, before vanishing from there and never showing up in the desktop.

I even tried to update the executable name in the .desktop file, since this change wasn't pushed into the latest Flathub version, but it didn't work.

## What did you expect to happen
App would start when launched from GNOME Shell

## What happened
App did not start when launched from GNOME Shell, but did start fine then launched from Terminal or GNOME Software. 

## Steps to reproduce
1 - Install Window Painter as a Flatpak from Flathub via GNOME Software
2 - Try to launch it from GNOME Shell

**Comment by Tuba2** [comment]
My bad, I had fixed only one of the .desktop files (the one in /files/share/dev.jamiethalacker.window_painter.desktop).

After I fixed both (the aforementioned and the one in /exports/share/dev.jamiethalacker.window_painter.desktop) the app launches just fine from GNOME Shell.

Sorry about that and thanks for the great game.

**Comment by ItsJamie9494** [comment]
Thanks for the reminder to update the Flathub manifest, by the way!

**Comment by Tuba2** [comment]
It will make the experience even better for new users. Congrats on the game!
